/* Default theme of the Bob engine */

* {
	FontSize: 14;
	FontName: data/bob/LiberationSerif-Regular.ttf;
}

Window {
	Image: data/bob/window.png;
	AreaImage: data/bob/window_area.png;
	TitleBarImage: data/bob/window_title_bar.png;
	
	HandleImage: data/bob/window_handle.png;
	HandleSize: 10;
}

Button {
	Image: data/bob/box.png;
}

Button:PRELIGHT {
	Image: data/bob/box_prelight.png;
}

Button:ACTIVE {
	Image: data/bob/box_active.png;
}

Entry {
	Image: data/bob/entry.png;
}
