name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }} SFML ${{ matrix.sfml.version }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows VS2026, os: windows-2025 }
        - { name: Linux GCC,      os: ubuntu-26.04 }
        - { name: Linux Clang,    os: ubuntu-26.04, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: macOS x64,      os: macos-26-intel }
        - { name: macOS arm64,    os: macos-26 }
        config:
        - { name: Shared, flags: -DBUILD_SHARED_LIBS=ON -DSFGUI_BUILD_SHARED_LIBS=ON -DSFML_STATIC_LIBRARIES=OFF }
        - { name: Static, flags: -DBUILD_SHARED_LIBS=OFF -DSFGUI_BUILD_SHARED_LIBS=OFF -DSFML_STATIC_LIBRARIES=ON }
        sfml:
        - { version: 3.0.2 }
        - { version: 3.1.0 }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libfreetype-dev libharfbuzz-dev libmbedtls-dev libssh2-1-dev

    - name: SFGUI - Checkout Code
      uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: SFML - Checkout Code
      uses: actions/checkout@v7
      with:
        repository: SFML/SFML
        ref: ${{ matrix.sfml.version }}
        path: SFML
        persist-credentials: false

    - name: SFML - Configure CMake
      env:
        CMAKE_FLAGS: ${{ matrix.platform.flags }} ${{ matrix.config.flags }}
      run: cmake -S "$GITHUB_WORKSPACE/SFML" -B "$GITHUB_WORKSPACE/SFML/build" -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/SFML/install" -DCMAKE_VERBOSE_MAKEFILE=ON $CMAKE_FLAGS

    - name: SFML - Build
      run: cmake --build "$GITHUB_WORKSPACE/SFML/build" --config Release --target install

    - name: SFGUI - Configure CMake
      env:
        CMAKE_FLAGS: ${{ matrix.platform.flags }} ${{ matrix.config.flags }}
      run: cmake -S "$GITHUB_WORKSPACE" -B "$GITHUB_WORKSPACE/build" -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install" -DCMAKE_VERBOSE_MAKEFILE=ON -DSFGUI_BUILD_EXAMPLES=ON -DSFML_DIR="$GITHUB_WORKSPACE/SFML/install/lib/cmake/SFML" $CMAKE_FLAGS

    - name: SFGUI - Build
      run: cmake --build "$GITHUB_WORKSPACE/build" --config Release --target install
